- README.md
this way the definition above of the enum MyIntEnum is sufficient to
understand the example code.
> rename SmallInt to Int in example

- README.md
different was written twice in a row. One should suffice
> Remove double different

- CHANGELOG.md
- Cargo.toml
- doc/display.md
- src/add_like.rs
- src/display.rs
- src/from.rs
- src/into.rs
- src/lib.rs
- src/mul_like.rs
- src/not_like.rs
- src/try_into.rs
- src/utils.rs
- tests/boats_display_derive.rs
- tests/display.rs
- tests/generics.rs
Allows stuff like the following:
```rust
enum E {
#[display(fmt = "A({:o})", "_0")]
A(u32),
#[display(fmt = "B {i: {:b})", "i + 29")]
B {i: i32},
}
```
The only issue is that you have to wrap arguments in strings, even though they are expressions. This is a limitation with the rust syntax, but I find this better than what `failure` does (only allows identifiers) since it's tedious to display paths with `failure`.
There's 2 semi-hacks in my PR:
- Errors aren't always reported with proper spans, since some times rustc loses the information somehow (see [this](https://github.com/dtolnay/syn/issues/508))
- The output of each derivation function is extended to allow `Results`, by utilizing traits. Perhaps this should not be used, and each derivation function should always …
> Upgrade to syn 0.15 and extend Display-like derivations to support custom formats

- src/display.rs
- tests/display.rs
Fixes #62.
To suppress `unused_variables` warnings, there are two ways:
- Add `#[allow(unused_variables)]` to `fn`
- Add `#[automatically_derived]` to `impl`
`automatically_derived` is a built-in attribute that suppresses "unused" warnings. [It has been "ungated" since at least Rust 1.4](https://github.com/rust-lang/rust/blame/780658a464603fa755d94b27f72a375bd81d07ea/src/libsyntax/feature_gate.rs#L792). But I could not find description about `automatically_derived` except
[a Stack Overflow answer](https://stackoverflow.com/questions/51481551/what-does-automatically-derived-mean) and it does not seem to be popular. So I just added `#[allow(unused_variables)]` to `fn fmt`.
<https://github.com/search?q=language%3Arust+automatically_derived&type=Code> …
> Suppress `unused_variable` warnings

- Cargo.toml
It works fine with 0.2.0, and it avoids pulling more
dependencies in https://phabricator.services.mozilla.com/D17028.
> Don't require a specific minor version of rustc_version.

- src/not_like.rs
Other traits received the inline attribute but this one was accidentally missed.  Fixes #70
> Add inline attribute to Neg and Not traits

- src/try_into.rs
- tests/try_into.rs
Code such as this (untested) breaks with `wrong number of type arguments: expected 1, found 2` due to the `TryInto` macro using a bare `Result`:
```
pub type Result<T> = core::result.Result<T, Error>;
#[derive(TryInto)]
pub enum Error { ... }
```
This PR fixes that problem by fully-qualifying the name.
> Fix unhygenic use of `Result` in `TryInto` macro

- Cargo.toml
- src/display.rs
- src/lib.rs
- tests/display.rs
Fixes #72
See #72 for the detailed issue description and motivation.
```rust
#[display(fmt = "{} {} {{0:p}} {0:o} {1:#x} - {0:>4?} {1:^4X?}", "_0", "_1")]
struct MultiTraitUnnamedGenericStruct<A, B>(A, B);
```
expands to
```rust
impl<A, B> ::std::fmt::Display for MultiTraitUnnamedGenericStruct<A, B>
where
A: ::std::fmt::Display + ::std::fmt::Debug + ::std::fmt::Octal,
B: ::std::fmt::Display + ::std::fmt::Debug + ::std::fmt::LowerHex,
{
// ...
}
```
- Apply the necessary trait bounds to type parameters __only if they are used__ in formatting expression.
- Detect the correct trait bound (`Display`, `Debug`, `Octal`, etc.) basing on [formatting placeholder format](https://doc.rust-lang.org/stable/std/fmt/index.html#syntax).
- Apply the necessary trait bounds for …
> Provide type parameter bounds for Display

- src/deref.rs
- src/deref_mut.rs
- tests/lib.rs
Derive `Deref` and `DerefMut` directly on any newtype structs's single field instead of requiring inner field to implement the traits.
This is a backwards-incompatible change, though many usages will require no call-site modification.
See issue #48 for discussion.
> Issue #48: derive `Deref` and `DerefMut` directly on any newtype structs

- src/constructor.rs
- src/deref.rs
- src/deref_mut.rs
- src/display.rs
- src/index_mut.rs
- src/try_into.rs
- tests/display.rs
- tests/no_std.rs
It'd be really nice to be able to derive `Display` and use an affix (prefix and/or suffix) that comes before each inner implementation of `Display`. This allows one to write a `derive`d implementation of `Display` like so:
```rust
// Expects a single Display item corresponding to where an inner 
// variant's Display will be written (`{}`), otherwise errors
#[derive(Debug, Display)]
#[display(affix = "unable to read from /proc/stat: {}")]
pub(crate) enum SnapshotReadError {
Io(IoError),
#[display(fmt = "expected CPU stat line for {}, got {:#?}", expected_cpu, line)]
UnableToParseLine {
expected_cpu: CpuComponent,
line: String,
}
}
#[derive(Debug, Display)]
pub(crate) enum CpuComponent {
#[display(fmt = "entire CPU")]
EntireCpu,
#[display(fmt = "CPU core {}", _0)]
Core(usize),
}
```
This …
> [WIP] Implement proof-of-concept of an enum "affix"

- Cargo.toml
- doc/as_mut.md
- doc/as_ref.md
- src/as_mut.rs
- src/as_ref.rs
- src/lib.rs
- src/utils.rs
- tests/as_mut.rs
- tests/as_ref.rs
Add derives for AsRef and AsMut traits, as discussed [here](https://github.com/JelteF/derive_more/issues/25#issuecomment-530168303).
> Derive AsRef and AsMut

- src/display.rs
- tests/display.rs
First half of #93.
Modified `Display` macro, so that for each field of the following types _or of reference to 
such types_ a where clause is generated bounding field's type by `Display` trait:
* `T`
* `T::AssociatedType` and `<T as Trait>::AssociatedType`
* `::path::SomeOtherType<T>` and `::path::SomeOtherType<&T>`
E.g., for a structure `Foo` defined like this:
```Rust
struct Foo<'a, T1, T2: Trait, T3> {
field1: T1,
field2: <T2 as Trait>::Type,
field3: Bar<T3>,
field4: &'a T1,
field5: &'a <T2 as Trait>::Type,
field6: &'a Bar<T3>,
}
```
Following where clauses would be generated (notice, that for reference types the 
_referred_ type is bound):
* `T1: Display`
* `<T2 as Trait>::Type: Display`
* `Bar<T3>: Display`
_As far as I understand,_ as we can't define `Display` for …
> WIP: Improve derive-Display trait bounds inference (#93)

- doc/display.md
- src/display.rs
- tests/display.rs
Second half of #93. This PR is based on top of #95.
Implemented `[display(bound = "...")]` attribute for `Display` macro as proposed by @tyranron in #93.
> Implement display-bound attribute for derive-Display macro (#93)

- src/deref.rs
- src/deref_mut.rs
- src/display.rs
- src/index.rs
- src/index_mut.rs
- src/into_iterator.rs
- tests/display.rs
Closes #107 
After having a look into the expanded code and wrapping my head around, I finally found the issue. the `Display` derive uses a helper struct for the case of an enum with nested format-strings like the following (taken from the tests):
```rust
#[display(fmt = "Here's a prefix for {} and a suffix")]
enum Affix {
A(u32),
#[display(fmt = "{} -- {}", wat, stuff)]
B {
wat: String,
stuff: bool,
},
}
```
The problem was that if there was no outer format string, the default `"{}"` would be used, which removes all formatting settings from properly propagating.
A quick workaround was to avoid the treacherous line `write!(f, "{}", helper_object)` and instead call `Display::fmt(&helper_object, f)` directly, so that's what I did in 2c74515. After I slowly became more …
> Refactor derive(Display) to properly propagate the alternate flag

- doc/from.md
With the addition of `ignore`, an impl for `u32` *is* generated and shown in the example.
> Fix description of example for From

- src/mul_assign_like.rs
- tests/mul_assign.rs
The code structure generated for AddAssign and MulAssign differs in what it supports: should we make AddAssign as permissive as MulAssign in that it accept a RHS as long as the underlying type’s operation will accept it?
> fix derivation of MulAssign for generic structs

- src/as_mut.rs
- src/as_ref.rs
- src/utils.rs
- tests/as_mut.rs
- tests/as_ref.rs
The current version adds the unnecessary (and syntactically incorrect) trait bound `impl<T: ::std::convert::AsRef>`.
I did the smallest amount of refactoring necessary to make the change, but of course there is always room for more.
> Fix generic trait bound for AsRef, AsMut

- src/display.rs
- src/utils.rs
"can not" -> "cannot" where appropriate
> Fixing typos

- src/utils.rs
- tests/lib.rs
This PR changes removes uses of the pattern `syn::parse_str(tokens.to_string())`,
which loses `Span` information. In addition to making error messages
less precise, it can break code that depends on the hygiene information
carried by `Span`. Instead, `syn::parse_quote` is used to parse a
`TokenStream` into the desired AST struct.
I've added a test which demonstrates one of the problems with
the previous code - using `$crate` would previously cause
a panic, but now compiles successfully.
> Avoid stringifying and reparsing a `TokenStream`

- tests/display.rs
Currently, [documentation for `Display`-like derives](https://jeltef.github.io/derive_more/derive_more/display.html) states:
> The variables available in the arguments is `self` and each member of the variant, with members of tuple structs being named with a leading underscore and their index, i.e. `_0`, `_1`, `_2`, etc.
...but this isn't tested anywhere. This PR adds this coverage.
---
Checklist:
> `Display`: test that we can use `self` at the top level

- src/error.rs
- src/into.rs
- src/utils.rs
- tests/from.rs
- tests/into.rs
This PR extends `types()` attribute in`From`/`Into` derives to support types more complex than a simple ident.
```rust
#[derive(From, Into)]
#[from(types("Cow<'_, str>", "&str"))]
#[into(owned(types("Cow<'_, str>")))]
struct Name(String);
```
> Allow complex additional types for From/Into

- doc/display.md
- src/error.rs
- src/sum_like.rs
- tests/display.rs
I noticed that you can use the self argument when deriving display (I dont know if this is a wanted feature).
So I thought to add a test and documentation for it.
> Add test and doc for display with self argument

- Cargo.toml
- build.rs
- doc/unwrap.md
- src/lib.rs
- src/unwrap.rs
- tests/unwrap.rs
```rust
#[derive(::derive_more::Unwrap)]
enum Lol {
Haha(i32),
Hm,
}
fn main() {
let a = Lol::Haha(10);
println!("Results: {:?}", a.unwrap_haha())
}
```
prints `Results: 10`, and switching to `a.unwrap_hm()` prints this message:
> thread 'main' panicked at 'called `Lol::unwrap_hm()` on a `Haha` value', src/main.rs:18:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Add Unwrap derive

- README.md
- doc/display.md
Per the comments in #68, this was missing from the docs.
I don't think the code in the `doc/` docs runs under `cargo test`, but I did check that my additions compile, run, and pass.
Closes #68
> Add documentation for DebugCustom derive

- src/mul_assign_like.rs
- src/mul_like.rs
This causes issues like we've already seen in #124.
Maybe it's possible to write some clippy lint to prevent imports of
HashSet/HashMap from std::collections. I don't know how to write one
though.
Fixes #177.
> Don't use collections::HashSet in derive impls

- Cargo.toml
- doc/from_str.md
- src/from_str.rs
- tests/from_str.rs
This allows deriving FromStr for enums with no fields in the obvious way
fixes #59
> Add support for #derive[FromStr] for enums

- CHANGELOG.md
- doc/error.md
- src/error.rs
- tests/error/nightly/derives_for_enums_with_backtrace.rs
- tests/error/nightly/derives_for_generic_enums_with_backtrace.rs
- tests/error/nightly/derives_for_generic_structs_with_backtrace.rs
- tests/error/nightly/derives_for_structs_with_backtrace.rs
- tests/error/nightly/mod.rs
- tests/error_tests.rs
Fixes #195 similar to https://github.com/dtolnay/thiserror/pull/182
> Replace `fn backtrace()` with `Provider` API in `Error` derive

- src/display.rs
This PR makes the generated code compatible with a global setting of  `#![deny(clippy::use_self)]` by using `Self::Variant` instead of `EnumName::Variant`.
> display: enum match arms: use 'Self' (to fix incompatibility with `#![deny(clippy::use_self)]`

- src/display.rs
- tests/display.rs
This removes a match arm that will never be triggered for non empty enums.
So now only if their are no arms in the enum will the code for empty enums be generated.
This changes no functionally and is a bug fix.
> Avoid branch in `Display` `match` statement for empty enums

- CHANGELOG.md
- src/add_assign_like.rs
- src/add_like.rs
- src/as_mut.rs
- src/as_ref.rs
- src/constructor.rs
- src/deref.rs
- src/deref_mut.rs
- src/display.rs
- src/error.rs
- src/from_str.rs
- src/index.rs
- src/index_mut.rs
- src/into.rs
- src/into_iterator.rs
- src/is_variant.rs
- src/mul_assign_like.rs
- src/mul_like.rs
- src/not_like.rs
- src/sum_like.rs
- src/try_into.rs
- src/unwrap.rs
Revealed from https://github.com/JelteF/derive_more/pull/192#issuecomment-1152091758  
The code, generated by `derive_more`, often becomes a subject of complains for strict style linters.
Use `#[automatically_derived]` attribute on any generated code, so the code style linters will omit the generated code.
> Use `#[automatically_derived]` attribute in each macro

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- impl/doc/try_into.md
- impl/src/try_into.rs
- src/errors.rs
- src/lib.rs
- tests/try_into.rs
Instead of returning a string as the error, this returns a dedicated
error type. This has the big benefit that in case of an error it's
possible to get back the original value by using `error.input`.
Previously the original value would be dropped in case of an error.
Fixes #173
Fixes #130
> Use dedicated error type for TryInto errors

- .github/workflows/ci.yml
- ci/test_all_features.sh
`tomljson` fails to install on CI now due to newer Go versions: https://github.com/JelteF/derive_more/actions/runs/3987055224/jobs/6836368442#step:5:11
More info:  https://golang.org/doc/go-get-install-deprecation
Try to use `go install` instead, as the error message suggests.
> Fix installing `tomljson` on CI

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- impl/Cargo.toml
- src/lib.rs
Resolves #210
As discussed in #210 we want to disable all features by default in 1.0.
With the amount of derives that are part of this library the compile
time of the library itself becomes significant. This way we don't have
to worry about increasing people their compile time when adding more
derives.
On my machine compiling the `derive_more-impl` crate took ~4.5 seconds
when enabling all features. But when only enabling a single derive it
took 1.5 seconds.
Enabling all derives is still easy to do, by using the `full` feature.
> Disable all features by default

- impl/src/fmt/display.rs
- tests/compile_fail/display/mutlifield_enum_variant_without_attribute.rs
- tests/compile_fail/display/mutlifield_enum_variant_without_attribute.stderr
- tests/compile_fail/display/mutlifield_struct_without_attribute.rs
- tests/compile_fail/display/mutlifield_struct_without_attribute.stderr
Resolves https://github.com/JelteF/derive_more/pull/232#discussion_r1085791282
After redesign in #225, some test cases were left unchecked. 
Error on mutlifield struct or enum variant without formatting attribute in `Display`-like macros
> Error on mutlifield struct or enum variant without formatting attribute in `Display`-like macros

- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- tests/compile_fail/debug/legacy_bound_syntax.stderr
- tests/compile_fail/debug/legacy_fmt_syntax.stderr
- tests/compile_fail/display/legacy_bound_syntax.stderr
- tests/compile_fail/display/legacy_fmt_syntax.stderr
Resolves https://github.com/JelteF/derive_more/issues/244#issuecomment-1458625976
> Regarding the error message for the old syntax. It is too ambiguous in my opinion: It saids use `"{name}: {source}"` instead but the old syntax already has `"{name}: {source}"`! It took me a while to realize that I need to remove `fmt =`. The error would be better if it tells user what to remove instead of what to include.
Change error from 
```
error: legacy syntax, use `"Stuff({}): {}", bar` instead
--> tests/compile_fail/display/legacy_fmt_syntax.rs:2:10
|
2 | #[display(fmt = "Stuff({}): {}", "bar")]
|          ^
```
to
```
error: legacy syntax, remove `fmt =` and use `"Stuff({}): {}", bar` instead
--> tests/compile_fail/display/legacy_fmt_syntax.rs:2:10
|
2 | #[display(fmt = "Stuff({}): {}", "bar")]
| …
```
> Clarify legacy attribute syntax errors for `Dispaly`-like and `Debug` macros

- CHANGELOG.md
Cleanup of #254
> * The "Internal changes" sections under 0.7.1 and 0.9.0 have been removed - users of your library don't need (nor do they care) about internal details, so long as it works.
> * The section for 0.99.4 was retitled to include `[YANKED]`.
> * Certain changes, such as the MSRV changes, or the change about all features except `std` being disabled by default, were reworded. This is either for clarity, or to make them fit better as changelog entries.
> Make CHANGELOG.md adhere closer to the Keep A Changelog format

- impl/Cargo.toml
The packaged crate fails to build otherwise (because of the include_str in lib.rs)
> Add missing README.md include in impl/Cargo.toml

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- build.rs
- ci/test_all_features.sh
- impl/Cargo.toml
- impl/doc/error.md
- impl/src/error.rs
- impl/src/fmt/display.rs
- src/lib.rs
- src/vendor/thiserror/aserror.rs
- tests/error/derives_for_enums_with_source.rs
- tests/error/mod.rs
- tests/error_tests.rs
Resolves #261
The `Error` derive can be made to work well for the most part in
`no_std` environments by enabling `#![feature(error_in_core)]`. This
changes the `Error` derive slightly to import `Error` and related
traits from core, when the `std` feature is disabled.
In passing this also fixes actually running the nightly error tests. They were not actually run anymore because there was no `build.rs` file in the root of the repo, only in the `impl` package. So the `nightly` config was not available in tests.
> Support Error in no_std environments

- impl/src/fmt/debug.rs
- src/fmt.rs
- src/lib.rs
There were a whole bunch of exports and re-exports in the `fmt` module
of things that should not be public API of this crate, but instead are
implementation details. So this limits the amount of things we export
from that module, and it also moves the things we do export the
`__private` module.
> Move fmt module to __private module

- .github/workflows/ci.yml
- Cargo.toml
- impl/Cargo.toml
- impl/src/lib.rs
- src/lib.rs
We have a [broken build on docs.rs](https://docs.rs/crate/derive_more/1.0.0-beta.1/builds/868214) for the [latest release](https://github.com/JelteF/derive_more/releases/tag/v1.0.0-beta.1).
- Use `full` feature on docs.rs to build crate docs.
- Add the `full` feature to `derive_more-impl` crate too, just for the same purpose.
- Correct CI to check building docs exactly as they're built on docs.rs.
Switch to `rustdoc::all` lints.
> Fix docs on docs.rs

- impl/doc/debug.md
- impl/src/fmt/debug.rs
- tests/debug.rs
Resolves #281
See #281:
> ```rs
> struct NoDebug;
>                                      
> #[derive(derive_more::Debug)]
> struct HasDebug<T>(#[debug(skip)] T);
>                                      
> dbg!(HasDebug(NoDebug));
> ```
>
> I'd be fine with needing to manually specify something like `#[debug(bounds())]`.
Fix how `ignore`/`skip` attributes are considered in bounding of `derive(Debug)` macro.
> Lift trait bounds from `#[debug(skip)]` fields (#281)

- impl/src/fmt/mod.rs
- impl/src/utils.rs
- tests/compile_fail/debug/legacy_fmt_syntax.rs
- tests/compile_fail/debug/legacy_fmt_syntax.stderr
- tests/compile_fail/display/legacy_fmt_syntax.rs
- tests/compile_fail/display/legacy_fmt_syntax.stderr
Related to #225
Diagnostic introduced in #225 regarding old syntax usage, displays incorrect message in case formatting arguments are specified as identifiers (not string literals):
```rust
#[derive(derive_more::Display)]
#[display(fmt = "Stuff({}): {}", _0)]
pub struct Bar(String);
```
```
error: unknown attribute, expected `bound(...)`
--> tests/compile_fail/display/legacy_fmt_syntax.rs:8:11
|
8 | #[display(fmt = "Stuff({}): {}", _0)]
|           ^^^
```
In my experience, this situation happens very often in the wild.
Fix the diagnostic to consider ident formatting arguments properly.
> Fix legacy diagnostic for `Display`-like macros

- CHANGELOG.md
- impl/src/into_iterator.rs
- impl/src/utils.rs
- tests/into_iterator.rs
Resolves #208 
For generic structs, some derived IntoIterator bounds are based on the struct's type parameters, rather than the field used in the implementation.
Require only the type of the field used to be `IntoIterator`
I don't think this is a breaking change, since no program where the newly added bounds aren't satisfied would have compiled.
> Fix IntoIterator derived bounds (#208)

- CHANGELOG.md
- src/lib.rs
Resolves https://github.com/JelteF/derive_more/issues/259#issuecomment-1673947234
Add `derive_more::derive` module, re-exporting macros only.
> Add `derive` module

- impl/src/fmt/debug.rs
- tests/debug.rs
At the moment, `derive_more::Debug` fails to work with `?Sized` generics:
```rust
#[derive(derive_more::Debug)]
struct UnnamedGenericStructUnsized<T: ?Sized>(T);
```
And generates the following error:
```
error[E0277]: the size for values of type `T` cannot be known at compilation time
--> tests/debug.rs:845:14
|
845 |     #[derive(Debug)]
|              ^^^^^ doesn't have a size known at compile-time
846 |     struct UnnamedGenericStructUnsized<T: ?Sized>(T);
|                                        - this type parameter needs to be `std::marker::Sized`
|
= note: required for the cast from `&T` to `&dyn Debug`
= note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider borrowing the value, since `&&T` can be …
```
> Fix `?Sized` type parameters in `Debug`

- CHANGELOG.md
- impl/doc/error.md
- impl/src/error.rs
- tests/error/nightly/derives_for_enums_with_backtrace.rs
- tests/error/nightly/derives_for_generic_enums_with_backtrace.rs
- tests/error/nightly/derives_for_generic_structs_with_backtrace.rs
- tests/error/nightly/derives_for_structs_with_backtrace.rs
- tests/error/nightly/mod.rs
- tests/error_tests.rs
Update derive and tests to work on the latest nightly with the changes in [this PR](https://github.com/rust-lang/rust/pull/113464).
Use `error::{Request, request_ref, request_value}` instead of `any::{Demand, request_ref, request_value}`
Currently `request_value` is not re-exported from `core::error` in `std::error`, which means backtrace tests require `#![feature(error_in_core)]`
Presumably this is a bug, and will be fixed later
> Fix generated `Error::provide` and tests to reflect changes in API

- CHANGELOG.md
- Cargo.toml
- README.md
- impl/Cargo.toml
- impl/src/as/mod.rs
- impl/src/lib.rs
- impl/src/utils.rs
- src/lib.rs
First suggested [here](https://github.com/JelteF/derive_more/pull/286#issuecomment-1678901955)
`AsRef` and `AsMut` derives are effectively the same regarding implementation, so using separate features for them doesn't make sense.
Use the `as_ref` feature for both derives
> Unite `as_ref` and `as_mut` features

- impl/doc/as_mut.md
- impl/doc/as_ref.md
- impl/doc/debug.md
- impl/doc/from.md
- impl/doc/into.md
- impl/src/fmt/debug.rs
- impl/src/from.rs
- impl/src/into.rs
- impl/src/utils.rs
First suggested [here](https://github.com/JelteF/derive_more/pull/286#discussion_r1297046342)
There's some repetition around parsing the same attributes in different derives
Refactor `Into`, `From`, and `Debug` derives to use the `skip` and `forward` attribute parsing utils
> Use the new parsing utils

- .github/workflows/ci.yml
- CHANGELOG.md
- impl/Cargo.toml
- impl/doc/as_mut.md
- impl/doc/as_ref.md
- impl/src/as/mod.rs
- impl/src/lib.rs
- impl/src/parsing.rs
- impl/src/utils.rs
- src/as.rs
- src/lib.rs
- tests/as_mut.rs
- tests/as_ref.rs
- tests/compile_fail/as_mut/multiple_struct_attrs.stderr
- tests/compile_fail/as_mut/renamed_generic.rs
- tests/compile_fail/as_mut/renamed_generic.stderr
- tests/compile_fail/as_mut/struct_attr_tuple.rs
- tests/compile_fail/as_mut/struct_attr_tuple.stderr
- tests/compile_fail/as_mut/unknown_field_attr_arg.stderr
- tests/compile_fail/as_mut/unknown_struct_attr_arg.stderr
- tests/compile_fail/as_ref/multiple_struct_attrs.stderr
- tests/compile_fail/as_ref/renamed_generic.rs
- tests/compile_fail/as_ref/renamed_generic.stderr
- tests/compile_fail/as_ref/struct_attr_tuple.rs
- tests/compile_fail/as_ref/struct_attr_tuple.stderr
- tests/compile_fail/as_ref/unknown_field_attr_arg.stderr
- tests/compile_fail/as_ref/unknown_struct_attr_arg.stderr
Resolves #285 
The `AsRef`/`AsMut` derives are less powerful than `From` and `Into`, because there's no way to specify types into which forwarded implementations should convert.
Keep using the `forward` attribute argument for blanket forwarded impls, and use a list of types for selective ones.
> Selective AsRef/AsMut impl

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- clippy.toml
- impl/Cargo.toml
- impl/doc/try_from.md
- impl/src/lib.rs
- impl/src/parsing.rs
- impl/src/try_from.rs
- src/convert.rs
- src/lib.rs
- tests/compile_fail/try_from/invalid_repr.rs
- tests/compile_fail/try_from/invalid_repr.stderr
- tests/compile_fail/try_from/struct.rs
- tests/compile_fail/try_from/struct.stderr
- tests/compile_fail/try_from/union.rs
- tests/compile_fail/try_from/union.stderr
- tests/try_from.rs
Resolves #146
Conversion from the repr integer to an enum.
A `TryFrom` derive macro implementing `TryFrom<integertype> for Enum`.
> Add `TryFrom` to convert repr to enum

- impl/src/into.rs
- tests/into.rs
Types are not always merged correctly when multiple `#[into]` attributes are specified.
```rust
#[derive(Clone, Copy, Debug, Into)]
#[into(ref)]
#[into(owned)]
#[into((Wrapped<i32>, Transmuted<f32>))]
#[into(ref_mut((Wrapped<i32>, Transmuted<f32>)))]
struct Tuple(
Wrapped<i32>,
Wrapped<f32>,
);
```
expands as
```rust
#[automatically_derived]
impl ::core::convert::From<Tuple> for (Wrapped<i32>, Transmuted<f32>) {
#[inline]
fn from(value: Tuple) -> Self { (<Wrapped<i32> as ::core::convert::From<_>>::from(value.0), <Transmuted<f32> as ::core::convert::From<_>>::from(value.1)) }
}
#[automatically_derived]
impl<'__derive_more_into> ::core::convert::From<&'__derive_more_into Tuple> for (&'__derive_more_into Wrapped<i32>,
&'__derive_more_into Wrapped<f32>) {
#[inline]
fn from(value: …
```
> Fix merging types in multiple `#[into]` attributes

- impl/src/try_into.rs
- src/as.rs
- tests/debug.rs
This crate contained some minor spelling mistakes.
I fixed some typos that I found with [`typos`](https://github.com/crate-ci/typos).
- [x ] Documentation is updated (if required)
- [ x] Tests are added/updated (if required)
> Fixed typos

- impl/src/fmt/mod.rs
- tests/display.rs
Resolves #319
See https://github.com/JelteF/derive_more/issues/319#issue-2004684216:
> The following code used to work in 1.0.0-beta.3:
> 
> ```rust
> #[derive(Display)]
> #[display("{name}@{tag}")]
> #[display(bound(Tag: std::fmt::Display))]
> struct Specifier<Tag> {
>     name: String,
>     tag: Tag,
> }
> ```
> 
> However, in 1.0.0-beta.6, it emits the following error message:
> 
> ```
> error: multiple `#[display("...", ...)]` attributes aren't allowed
> ```
> 
> It took me a long time to figure out that the fix was to swap place between the 2 display attributes.
The regression lies [here](https://github.com/JelteF/derive_more/blob/v1.0.0-beta.6/impl/src/fmt/mod.rs#L394-L399), where `mem::replace` doesn't provide the implied and expected "and" logic for merging two `Option`s.
[l:1]: …
> Fix order sensitivity of `Display` attributes (#319)

- CHANGELOG.md
- impl/doc/debug.md
- impl/doc/display.md
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- impl/src/fmt/parsing.rs
- impl/src/parsing.rs
- impl/src/utils.rs
- tests/debug.rs
- tests/display.rs
Resolves #321
See https://github.com/JelteF/derive_more/issues/321#issuecomment-1854069597:
> You’re discarding formatting flags provided by the user in format string, e.g.:
> 
> ```rust
> #[derive(derive_more::Display)]
> #[display(fmt = "{:?}", _0)]
> struct Num(usize);
> 
> impl std::fmt::Debug for Num {
>     fn fmt(&self, fmtr: &mut std::fmt::Formatter) -> std::fmt::Result {
>         self.0.fmt(fmtr)
>     }
> }
> 
> fn main() {
>     let num = Num(7);
>     println!("{num:03?}");  // prints ‘007’ as expected
>     println!("{num:03}");   // prints ‘7’ instead
> }
> ```
See https://github.com/JelteF/derive_more/issues/321#issuecomment-1854382465:
> Theoretically, we can support this with the current syntax, because we can detect so-called _trivial_ cases and transform them into …
> Delegation for `fmt` traits (#321)

- README.md
Since the README is already listing derives that don't even exist in the
current stable version, lets just all point them to the beta docs. The
beta is currently the version I recommend people to use anyway, although
I warn them that some small breaking changes are incoming.
Fixes #323
> Update links to derive docs in README to point to beta

- .github/workflows/ci.yml
- impl/src/as/mod.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- impl/src/from.rs
- impl/src/into.rs
- impl/src/parsing.rs
- impl/src/try_from.rs
- impl/src/utils.rs
We do have quite a rich private documentation, which helps to understand and navigate code. However, it has never been checked on CI, so many intra-doc links are just broken.
> Fix private docs

- CHANGELOG.md
- impl/src/add_assign_like.rs
- impl/src/add_like.rs
- impl/src/as/mod.rs
- impl/src/error.rs
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/from.rs
- impl/src/from_str.rs
- impl/src/into.rs
- impl/src/not_like.rs
- impl/src/sum_like.rs
- impl/src/try_from.rs
- impl/src/try_into.rs
- impl/src/utils.rs
- src/lib.rs
Resolves #180
See https://github.com/JelteF/derive_more/issues/180#issue-1091650576 for details.
At the moment, compilation fails in a local crate `core` is present in workspace or some another crate is renamed as `core`.
Use `::derive_more::core` instead of `::core` in macro expansions.
> Better hygiene for `core` crate naming (#180)

- README.md
Resolves #330
> Instructions to specify features in README are wrong. 
> it should be
>
> ```
> derive_more = { version='...', features = [...]}
> ```
> Fix specifying features in README (#330)

- Cargo.toml
The description of this category fits derive_more quite well:
> Shared solutions for particular situations specific to programming in Rust.
> Add rust-patterns as a category

- CHANGELOG.md
- impl/src/error.rs
- impl/src/fmt/debug.rs
- impl/src/is_variant.rs
To be clear the `#[inline]` does not hint that inlining is beneficial,
but it does give the compiler the option to inline if the compiler
things it would be beneficial.
This starts adding the `#[inline]` attribute to:
1. `IsVariant`: it's expected that this is often beneficial since its
body is tiny.
2. `Debug`: This is to stay in line with the `std` implementation of the
`Debug` derive. https://github.com/rust-lang/rust/pull/117727
It also explicitely doesn't add the attribute to the methods of `Error`,
since those are almost never called in hot code paths.
Fixes #317
> Add #[inline] attribute to a few more methods

- impl/Cargo.toml
- tests/debug.rs
Related to #301
[`syn`  2.0.45 fixes](https://github.com/dtolnay/syn/issues/1513#issuecomment-1873450968) the #301 issue:
> Otherwise this would not work:
> 
> ```rust
> #[derive(derive_more::Debug)]
> enum Enum {
>     A = if cfg!(unix) { 2 } else { 3 },
> }
> ```
> 
> ```
> error: proc-macro derive panicked
>  --> src/main.rs:1:10
>   |
> 1 | #[derive(derive_more::Debug)]
>   |          ^^^^^^^^^^^^^^^^^^
>   |
>   = help: message: called `Result::unwrap()` on an `Err` value: Error("unsupported expression; enable syn's features=[\"full\"]")
> ```
Upgrade minimal version of `syn` up to 2.0.45 version and cover the use case with tests for future regressions.
> Upgrade `syn` crate to 2.0.45 version

- CHANGELOG.md
- impl/src/is_variant.rs
Resolves #357 
Generated documentation is incorrect, see issue
Ensure `stringify!` happens after `quote!` interpolation
---
Something for consideration: https://matklad.github.io/2022/10/24/actions-permissions.html
> Fix variant name interpolation in documentation for `IsVariant`

- Cargo.toml
- impl/Cargo.toml
- impl/src/into.rs
- impl/src/utils.rs
I got a warning about this when trying to release 0.99.18
Also fix various clippy warnings.
> Include example published package

- impl/doc/try_from.md
- src/convert.rs
Resolves 
Part of 
Required for 
Requires 
Related to 
fix some comments
> chore: fix some comments

- CHANGELOG.md
- impl/src/add_assign_like.rs
- impl/src/add_like.rs
- impl/src/mul_assign_like.rs
- impl/src/mul_like.rs
Resolves #364
In debug builds overflows cause panics. With our derives it's hard to spot
where these panics happen when RUST_BACKTRACE is not set. 
This fixes that by marking our trait methods for Add/Mul(Assign) as `#[track_caller].
~- [ ] Documentation is updated (if required)~
~- [ ] Tests are added/updated (if required)~
> Add #[track_caller] to Add/Mul(Assign) derives

- src/lib.rs
Resolves #351
Rust-analyzer doesn't ignore `#[doc(hidden)]` exports when they use a glob
pattern, only when they explicitely re-export. 
This adds more level of indirection and one more glob pattern so that we put
`#[doc(hidden)]` on explicit re-exports. This definitely starts to feel like
we're doing hack upon hack here. But ah well, this seems to work. And working
well with the most popular LSP for Rust seems worth a bit of a hack.
> Work around bug in rust-analyzer to make auto-imports work nicely

- impl/src/fmt/debug.rs
Related to #289
Related to #328
While looking into #328 I realized the current situation around Pointer derives
and references was even weirder because we store a double-reference to the
fields in the local variables for Debug, but not for Display. The reason we
were doing this was because of #289.
This stops storing a double-reference, and only adds the additional reference
in the places where its needed.
> Don't use double ref vars in Debug derive

- tests/lib.rs
While doing other things I noticed that this test was commented out for
seemingly no reason.
> Re-enable commented out test

- CHANGELOG.md
- impl/Cargo.toml
- impl/doc/error.md
- src/lib.rs
- tests/no_std.rs
The `error_in_core` feature is not necessary anymore when building, because the feature got [stabilized on nightly][1]. Now it's just a waiting game until it is on actual stable Rust. This updates the documentation accordingly, as well as adding some `no_std` tests for Error.
[1]: https://github.com/rust-lang/rust/pull/125951
> Update documentation about Error in no_std

- impl/src/try_into.rs
- tests/generics.rs
- tests/try_into.rs
Part of #335
Our `TryFrom` derive would fail when the type had any generics, this was a bug introduced with our changes for 1.0.
This fixes that by correctly adding the generic parameters to the `Error` type of `TryFrom`.
> Fix TryInto derive for generics

- ci/test_all_features.sh
- tests/debug.rs
- tests/deref_mut.rs
- tests/display.rs
When running no_std tests I realised there were warnings. This removes all of
them and configures CI to complain when this happens next.
> Remove unused imports for no_std tests

- impl/src/fmt/debug.rs
- tests/debug.rs
- tests/sum.rs
Resolves #363
Well, at least it's a suggestion for a resolution :p
The problem, as reported in the issue, is that code like the following
```rust
#[derive(derive_more::Debug)]
struct Item {
next: Option<Box<Item>>,
}
```
expands into something like
```rust
impl std::fmt::Debug for Item where Item: Debug { /* ... */ }
```
which does not compile. This PR changes the Debug derive so it does not emit those bounds.
My understanding of the current code is that we iterate over all fields of the struct/enum and add either a specific
format bound (e.g. `: fmt::Binary`), a default `: fmt::Debug` bound or skip it if either it is marked
as `#[debug(skip)]` or the entire container has a format attribute. 
The suggested solution in the issue (if I understood it correctly) was to only add bounds if the …
> Only put Debug-like bounds on type variables

- CHANGELOG.md
- impl/doc/debug.md
- impl/doc/display.md
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- impl/src/parsing.rs
- tests/debug.rs
- tests/display.rs
Resolves #328
Requires #377
Requires #380 
`Debug` and `Display` derives allow referring fields via short syntax (`_0` for unnamed fields and `name` for named fields):
```rust
#[display("{_0:o}")]
struct OctalInt(i32);
```
The way this works is by introducing a local binding in the macro expansion:
```rust
let _0 = &self.0;
```
This, however, introduces double pointer indirection. For most of the `fmt` traits, this is totally OK. However, the `fmt::Pointer` is sensitive to that:
```rust
#[display("--> {_0:p}")]
struct Int(&'static i32);
// expands to
impl fmt::Display for Int {
fn fmt(&self, f: fmt::Formatter<'_>) -> fmt::Result {
let _0 = &self.0; // has `&&i32` type, not `&i32`
write!(f, "--> {_0:p}") // so, prints address of the `_0` local binding, …
```
> Fix incorrect `fmt::Pointer` implementations attempt two

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- impl/Cargo.toml
- impl/doc/try_from.md
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- tests/try_from.rs
Resolves https://github.com/JelteF/derive_more/pull/381#discussion_r1698786709
It has sense to bump MSRV to 1.75 for using RPITIT in implementations.
> Bump up MSRV to 1.75

- impl/release.toml
During my dry-run release I noticed there were two tags being created,
one for each crate. That's rather useless since they will always point
to the same commit, so this disables creating the tag for the
derive_more-impl crate.
> Don't create git tags for derive_more-impl

- tests/compile_fail/debug/lifetime_no_debug.rs
- tests/compile_fail/debug/lifetime_no_debug.stderr
Resolves #392
Related to #371
Before #371 this code would compile without any issues, but that would actually
hide the problem that the resulting `Debug` implementation was never
applicable, because the bounds could not be satisfied.
This problem was already solved by #371, but this adds a test case to ensure
that we don't regress here again.
> Add compile_fail test for on purpose limited bounds

- CHANGELOG.md
- impl/src/fmt/mod.rs
- tests/debug.rs
- tests/display.rs
Related to #387
After #387, the following snippet fails to compile:
```rust
#[derive(Debug)]
struct AssocType<I: Iterator> {
iter: I,
elem: Option<I::Item>,
}
```
This happens, because the implied bound `Option<I::Item>: Debug` is not generated.
Correct the `ContainsGenericsExt::contains_generics()` implementations to consider associated types of the type parameter.
> Consider associated types of type parameters for implied bounds

- CHANGELOG.md
- impl/src/as/mod.rs
- impl/src/constructor.rs
- impl/src/deref.rs
- impl/src/deref_mut.rs
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/from.rs
- impl/src/is_variant.rs
- impl/src/not_like.rs
- impl/src/try_unwrap.rs
- impl/src/unwrap.rs
- tests/as_mut.rs
- tests/as_ref.rs
- tests/constructor.rs
- tests/debug.rs
- tests/deref.rs
- tests/deref_mut.rs
- tests/display.rs
- tests/from.rs
- tests/is_variant.rs
- tests/not.rs
- tests/try_unwrap.rs
- tests/unwrap.rs
Resolves #400
For `!` never type used in trait signatures, `rustc` emits `unreachable_code` warning ignoring the `#[automatically_derived]` attribute.
Add `#[allow(unreachable_code)]` to generated `impl`s to suppress such warnings for `!` and similar types.
> Add `#[allow(unreachable_code)]` to generated impls for `!` type

- README.md
Resolves 
Part of 
Required for 
Requires 
Related to
> fix: README feature `iterator` does not exist, now `into_iterator`

- ci/test_all_features.sh
- tests/lib.rs
Resolves #420
`cargo test --no-default-features --features=full` fails imposing problems on other CIs.
See #420 for more context.
- Consider testing `full` Cargo feature in `test-features` CI job to handle such regressions.
- Update the relevant tests to run under `no_std` too.
> Test `full` feature separately on CI

- CHANGELOG.md
- impl/doc/display.md
- impl/src/fmt/display.rs
- tests/display.rs
Follows #377  
Resolves #411
At the moment, the following example:
```rust
#[derive(Debug, Display)]
#[display("{self:?}")]
enum Enum {
#[display("A {_0}")]
A(i32),
#[display("B {}", field)]
B { field: i32 },
C,
}
```
expand incorrectly as:
```rust
#[automatically_derived]
impl derive_more::Display for Enum {
fn fmt(&self, __derive_more_f: &mut derive_more::core::fmt::Formatter<'_>) -> derive_more::core::fmt::Result {
match self {
Self::A(_0) => { derive_more::core::write!(__derive_more_f, "A {_0}", _0 = *_0) }
Self::B {
field
} => { derive_more::core::write!(__derive_more_f, "B {}", field, ) }
Self::C => { __derive_more_f.write_str("C") }
} 
} 
}
```
This is because transparency check of the shared `#[display(...)]` formatting attribute doesn't consider the actual trait, called …
> Fix transparency and behavior of shared attribute formatting on enums (#377, #411)

- CHANGELOG.md
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- tests/debug.rs
- tests/display.rs
Resolves #431
See https://github.com/JelteF/derive_more/issues/431#issue-2761055237:
> Both of the following generate a working impl:
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct<T> {
>     thing: T,  // generic
> }
> ```
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct {
>     r#thing: i32,  // raw
> }
> ```
> 
> but this generates an impl that does not compile.
> 
> ```rust
> #[derive(Display)]
> #[display("{thing}")]
> struct Struct<T> {
>     r#thing: T,  // raw, generic
> }
> ```
> 
> ```
> error[E0277]: `T` doesn't implement `derive_more::Display`
>  --> src/main.rs:3:10
>   |
> 3 | #[derive(Display)]
>   |          ^^^^^^^ `T` cannot be formatted with the default formatter
>   |
>   = note: in format strings you may be able to …
```
> Fix raw identifiers usage in `Display`/`Debug` derives (#431)

- CHANGELOG.md
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/fmt/mod.rs
- tests/display.rs
The transparency is not considered when the top-level shared `#[display(...)]` attribute on enum uses a field directly.
```rust
#[display("{_0}")]
enum Foo<A> {
A(A),
}
assert_eq!(format!("{:03}", Foo::<i8>::A(7)), "007");
```
results in:
```
assertion `left == right` failed
left: "7"
right: "007"
```
Consider field's transparency for the top-level shared `#[display(...)]` attribute.
> Fix transparency for top-level shared attribute in `Display`

- CHANGELOG.md
- impl/src/fmt/mod.rs
- tests/debug.rs
- tests/display.rs
Resolves #432
See https://github.com/JelteF/derive_more/issues/432#issue-2761083580:
> ```rust
> use derive_more::Display;
> 
> #[derive(Display, Debug)]
> #[display("{head}.{tail}")]
> struct Struct {
>     head: char,
>     tail: str,
> }
> 
> fn main() {
>     let dat = [51i32, 3028017];
>     let s = unsafe { &*(&raw const dat as *const [i32] as *const Struct) };
>     println!("{:?}", s);
>     println!("{}", s);
> }
> ```
> 
> The derived Debug impl prints `Struct { head: '3', tail: "14" }` but the Display impl does not compile.
> 
> ```
> error[E0277]: the size for values of type `str` cannot be known at compilation time
>    --> src/main.rs:3:10
>     |
> 3   | #[derive(Display, Debug)]
>     |          ^^^^^^^ doesn't have a size known at compile-time
> 4   | …
```
> Fix unsized fields usage in `derive(Display)` (#432)

- Cargo.toml
derive_more is being pulled into the playground due to being a
dependency of some other crate in the top 100 crates, probably
<https://docs.rs/selectors>.
This adds metadata so that it gets installed with all features once
selectors updates to derive_more 2.0
> Add Rust Playground metadata

- CHANGELOG.md
- impl/src/as/mod.rs
- impl/src/constructor.rs
- impl/src/deref.rs
- impl/src/deref_mut.rs
- impl/src/fmt/debug.rs
- impl/src/fmt/display.rs
- impl/src/from.rs
- impl/src/into.rs
- impl/src/is_variant.rs
- impl/src/not_like.rs
- impl/src/try_from.rs
- impl/src/try_unwrap.rs
- impl/src/unwrap.rs
- tests/as_mut.rs
- tests/as_ref.rs
- tests/constructor.rs
- tests/debug.rs
- tests/deref.rs
- tests/deref_mut.rs
- tests/display.rs
- tests/from.rs
- tests/is_variant.rs
- tests/not.rs
- tests/try_unwrap.rs
- tests/unwrap.rs
Resolves #419
Deprecating a field or variant doesn't produced un-ignorable warnings in the code generated  by derive_more (the only solution was to globally `#![allow(deprecated)]` in the whole module).
Adds `allow(deprecated)` to the generated code.
>  fix: Ignore deprecation warnings on generated code

- tests/debug.rs
- tests/display.rs
Resolves #451
See https://github.com/JelteF/derive_more/issues/451#issue-2944740767:
> I am working on updating the Fedora Linux packages for this crate, and encountered some new test failures on the s390x-unknown-linux-gnu build target (our only supported big-endian architecture).
> 
> From `tests/debug.rs`:
> 
> ```
> ---- structs::multi_field::r#unsized::assert stdout ----
> thread 'structs::multi_field::r#unsized::assert' panicked at tests/debug.rs:794:17:
> assertion `left == right` failed
>   left: "Tuple('3', \"\\0.\")"
>  right: "Tuple('3', \"14\")"
> 
> ---- structs::multi_field::r#unsized::interpolated::assert stdout ----
> thread 'structs::multi_field::r#unsized::interpolated::assert' panicked at tests/debug.rs:836:21:
> assertion `left == right` failed
>   left: "3.\0."
> …
```
> Run tests dependent on endianess under `cfg` (#451)

- CHANGELOG.md
- impl/src/try_from.rs
- tests/compile_fail/try_from/invalid_repr.rs
- tests/compile_fail/try_from/invalid_repr.stderr
- tests/compile_fail/try_from/no_repr.rs
- tests/compile_fail/try_from/no_repr.stderr
Resolves #457
See https://github.com/JelteF/derive_more/issues/457#issue-3014360584:
> If the attribute is required, its absence should generate a compile error. If it's not required, then omitting it should not result in doing nothing.
Error if no `#[try_from(repr)]` is provided on enum.
> Error when no `#[try_from(repr)]` is provided (#457)

- CHANGELOG.md
- impl/doc/error.md
- impl/src/error.rs
- tests/error/derives_for_enums_with_source.rs
- tests/error/derives_for_generic_enums_with_source.rs
- tests/error/derives_for_generic_structs_with_source.rs
- tests/error/derives_for_structs_with_source.rs
Resolves #426
See https://github.com/JelteF/derive_more/issues/426#issue-2688714756:
> I’d like to be able to use `derive_more` with optional sources, like:
> ```rust
> #[derive(derive_more::Error, derive_more::Display, Debug)]
> #[display("it’s an error")]
> struct MyErr {
>     source: Option<Box<dyn std::error::Error + Send + Sync + 'static>>,
> }
> ```
The way, the `thiserror` does it, is by [checking](https://docs.rs/thiserror-impl/2.0.12/src/thiserror_impl/expand.rs.html#50) the [type name to contain `Option`](https://docs.rs/thiserror-impl/2.0.12/src/thiserror_impl/expand.rs.html#559-583). Relying on type could be fragile, as the call site could introduce its own type named `Option` in the scope where macro is called. Ideally, we need to aid this case with type machinery.
For …
> Support optional `Error::source` (#426)

- impl/doc/error.md
- impl/src/error.rs
- impl/src/utils.rs
- tests/error/derives_for_enums_with_source.rs
- tests/error/derives_for_generic_enums_with_source.rs
- tests/error/derives_for_generic_structs_with_source.rs
- tests/error/derives_for_structs_with_source.rs
Resolves #426    
Follows #459
See #459:
> Additionally, we may support `#[error(source(optional))]` attribute, which will allow using renamed types naturally:
> ```rust
> use derive_more::{Display, Error};
>
> #[derive(Debug, Display, Error)]
> struct Simple;
>
> #[derive(Debug, Display, Error)]
> #[display("Oops!")]
> struct Generic(#[error(source(optional))] RenamedOption<Simple>); // forces recognizing as `Option`
> type RenamedOption<T> = Option<T>;
> ```
Adds support for `#[error(source(optional))]` attribute.
> Support `#[error(source(optional))]` attribute (#426)

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- impl/Cargo.toml
- impl/doc/error.md
- impl/src/error.rs
- src/add.rs
- src/convert.rs
- src/lib.rs
- src/ops.rs
- src/str.rs
- src/try_unwrap.rs
- src/vendor/thiserror/aserror.rs
- tests/error/derives_for_enums_with_source.rs
- tests/error/derives_for_structs_with_source.rs
- tests/error/mod.rs
- tests/try_into.rs
- tests/try_unwrap.rs
We had [TODOs across the code](https://github.com/JelteF/derive_more/blob/v2.0.1/impl/src/error.rs#L43-L44):
> ```rust
> // TODO: Use `derive_more::core::error::Error` once `error_in_core` Rust feature is
> //       stabilized.
> ```
The `feature(error_in_core)` was [stabilized in 1.81 Rust](https://github.com/rust-lang/rust/pull/125951).
It's long enough, so we can bump up our MSRV.
- Use `core::error::Error` in codebase and remove `feature = "std"` gating for it.
- Bump up MSRV to 1.81.
> Use `core::error::Error` in codebase

- CHANGELOG.md
- impl/Cargo.toml
- impl/src/as/mod.rs
- impl/src/utils.rs
- tests/as_mut.rs
- tests/as_ref.rs
Revealed from #473
`utils::GenericsSearch` doesn't consider associative type, leading to missing trait bounds in `AsRef`/`AsMut` expansions.
```rust
#[derive(AsRef)]
#[as_ref(forward)]
struct Forward<T: Some> {
first: T::Assoc,
}
```
expands as:
```rust
#[allow(deprecated)]
#[allow(unreachable_code)]
#[automatically_derived]
impl<T: Some, __AsT: ?derive_more::core::marker::Sized> derive_more::core::convert::AsRef<__AsT> for Forward<T>
{
#[inline]
fn as_ref(&self) -> &__AsT { <T::Assoc as derive_more::core::convert::AsRef<__AsT>>::as_ref(&self.first) }
}
```
but should expand as:
```rust
#[allow(deprecated)]
#[allow(unreachable_code)]
#[automatically_derived]
impl<T: Some, __AsT: ?derive_more::core::marker::Sized> derive_more::core::convert::AsRef<__AsT> for Forward<T>
where
T::Assoc: …
```
> Consider associative types in `utils::GenericsSearch`

- CHANGELOG.md
- impl/src/constructor.rs
- tests/constructor.rs
Resolves https://github.com/JelteF/derive_more/issues/397
Clippy emits a too_many_arguments warning for the new method generated by the Constructor derive.
Clippy attributes currently have no effect in this context.
Add #[allow(clippy::too_many_arguments)] to the generated new method to suppress the warning without affecting other code.
> Add attribute too_many_arguments to the new method for Construct
